services:
  postgres:
    image: postgres:16
    container_name: genderize-postgres
    environment:
      POSTGRES_DB: genderize_stage2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genderize-api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=genderize_stage2_db;Username=postgres;Password=postgres
      SeedData__Enabled: 'true'
      SeedData__FilePath: data/seed_profiles.json
    ports:
      - '127.0.0.1:8081:8080'

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    name: genderize-network
